### ISSUE TITLE
Conceptual question on longshot 

### ISSUE THREAD

**Issue by sparthib** [pjedge/longshot#100]
Hi, 
I am new to SNV calling and I was wondering if it makes sense to use longshot on nanopore direct cDNA data. I was also wondering if the tool can be used to perform isoform-level phasing. 

Thanks,
Sowmya

**Comment by vibansal** [comment]
Longshot could work on nanopore RNA reads. However, it will provide phasing of the two chromosomes and not isoform-level phasing.

**Comment by sparthib** [comment]
Thanks @vibansal! 

Following up on this, I have aligned my reads to a haploid human genome (GENCODE release 46). Can I perform Haplotyping from this or do I need to align my reads to a diploid human genome assembly in order to do that?

**Comment by vibansal** [comment]
Longshot works with a haploid reference genome

**Comment by sparthib** [comment]
Thanks @vibansal , as a follow up, would this work on reads aligned to a transcriptome instead of genome? I.e., if you wanted to phase isoforms instead of genes? Thanks!

Sowmya
