### ISSUE TITLE
haplotagged bam file

### ISSUE THREAD

**Issue by HLHsieh** [pjedge/longshot#104]
Hi there,

I was trying to haplotag bam file with longshot (v0.4.5) as follows

```
longshot -r chr9 --bam C9ORF72.sorted.bam --ref genome.fa --out output.vcf -O C9ORF72_tag.bam
```

However, no any haplotype tags (HP:i:1 and HP:i:2) was added to C9ORF72_tag.bam

Any suggestions would be appreciated.

Many thanks,
Hsin

**Comment by vibansal** [comment]
Check the longshot output to see if heterozygous variants were called and phased in the region of interest
