### ISSUE TITLE
Cannot read FASTA

### ISSUE THREAD

**Issue by erdikucuk** [pjedge/longshot#25]
Hi,

When I try to run Longshot, it panics like this:

```
[erdi@login03 longshot]$ ./target/release/longshot --bam /ifs/home/erdi/pacbiocov/PacBio_deNovo/data/hg38.PBRT01-f__DNA17-07725_sorted1.bam --ref /ifs/home/erdi/pacbiocov/PacBio_deNovo/data/GRCh38_no_alt_plus_hs38d1_concat_nonprimary.fa --out /ifs/home/erdi/pacbiocov/PacBio_deNovo/results/SNVcalling/try1.vcf

2018-11-13 14:02:02 Estimating alignment parameters...
thread 'main' panicked at 'Failed to read fasta sequence record.: Custom { kind: Other, error: StringError("Unknown sequence name.") }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I haven't changed sequence names in ref file from [the original file](https://dl.dnanex.us/F/D/6KYxb8YkzjfqYjf7jxBVQjxp5k4zGbPzB9VKqvJg/GRCh38_no_alt_plus_hs38d1_concat_nonprimary.fa.gz) so couldn't figure out what is causing the issue.

Thanks a a lot in advance!

Best,
Erdi

**Comment by pjedge** [comment]
Are there any sequences in the bam that are aligned to contigs not present in the fasta?

**Comment by erdikucuk** [comment]
Hi, sorry for late response.  You were right,turns out my BAM files were corrupted. It is working perfectly now, thanks a lot!
