### ISSUE TITLE
FILTER 'dn' is not defined in the header

### ISSUE THREAD

**Issue by wdecoster** [pjedge/longshot#26]
Hi,

Thanks for this tool - looks very promising. bcftools spits out an error though:

```
[W::vcf_parse] FILTER 'dn' is not defined in the header
Error: The filter is not defined in the header: dn
```

Regards,
Wouter

**Comment by pjedge** [comment]
Thanks for the heads up! Will fix.

**Comment by pjedge** [comment]
fixed

**Comment by caonetto** [comment]
Hi, 
Do you know if this has been fixed in the conda install?? I am getting the same error with the latest conda.

**Comment by pjedge** [comment]
Hi,
I have not yet published the version with the fix.
I will do that now and should be on conda soon.

**Comment by caonetto** [comment]
Thank you Peter.

**Comment by pjedge** [comment]
keep an eye open for v0.3.4 on conda which has this fixed -- it was just merged there.
