### ISSUE TITLE
longshot and HiFi reads

### ISSUE THREAD

**Issue by sjin09** [pjedge/longshot#29]
To whom it may concern,

I am writing to inquire whether HiFi reads have been tested with longshot. I am testing the ability of longshot to call germline mutations with HiFi reads and I wanted to get some second option on this. In addition, I was wondering if --thread option could be added to longshot.

Best regards,
Sangjin Lee

**Comment by pjedge** [comment]
The current version of the code has not been tested with CCS reads. It
should work in principle, but the model has no optimizations for the
technology. There's also the challenge that indel variants will not be
properly detected. With regard to a multi-threading option, we plan to
introduce an auxiliary script to process chromosomes or chunks of the
genome in parallel with different processes.
