### ISSUE TITLE
Weird characters in error output

### ISSUE THREAD

**Issue by ptrebert** [pjedge/longshot#30]
Hi,
I just tested v0.3.4 of longshot and had a typo in the command line; big +1 for a tool properly catching this and even suggesting the correct alternative! However, when I opened the error log in vim, it contained some weird characters - maybe, you want to look into this at some point...

![longhsot](https://user-images.githubusercontent.com/36245614/63500531-49140f00-c4ca-11e9-9467-8875f2459d1c.png)

+Peter

**Comment by pjedge** [comment]
Thanks! Longshot makes use of a great command line parsing library for rust
called clap, which is what handles that cool feat. My initial impression is
to wonder if those characters are for specifying color formatting on the
terminal?

**Comment by ptrebert** [comment]
Ha, even highlighting is supported, amazing. Indeed, I just repeated this w/o sending the error output to a log file, and I can see the highlighting. Thanks for pointing that out.
