### ISSUE TITLE
vcf format interpretations

### ISSUE THREAD

**Issue by ShaokangZhang** [pjedge/longshot#31]
May I ask the annotations in the vcd files? Thanks.
What is "AM"? and what is its relationship to AC's two numbers?
Do you have a more detailed version on the annotations of VCF file from longshot? Thanks. 

Regards,
Shaokang

**Comment by vibansal** [comment]
AM corresponds to reads covering a variant for which the allele could be assigned with reasonably high confidence to one of the alleles. This can be useful to identify variants that are difficult to genotype. Currently, we don't have a more detailed description of the VCF INFO fields other than the description in the VCF itself.
