### ISSUE TITLE
15x coverage and 3-6% error rate?

### ISSUE THREAD

**Issue by GuillaumeHolley** [pjedge/longshot#32]
Hi there,

Do you think Longshot would work on a 15x coverage dataset of long reads (human) with an error rate somewhere in between 3 and 6%?

Thank you for the help.

Guillaume

**Comment by vibansal** [comment]
It should work, although the recall will be lower. We have tried it on 20x coverage PacBio data and recall was 4-5 percentage points lower compared to 40x coverage (at the same precision).

**Comment by GuillaumeHolley** [comment]
Alright, thanks for the info. I will definitely try it tomorrow then!
