### ISSUE TITLE
multiple regions

### ISSUE THREAD

**Issue by jdmontenegro** [pjedge/longshot#34]
Dear developers,
Thank you for this tool, it is very useful indeed. I wondered if there is a way to run multiple regions in a single command. I have a draft genome with multiple scaffolds (~1000) and I do not have the tools or budget to build pseudomolecules or chromosomes with thos scaffolds.  If I could run perhaps 200 jobs with 5 scaffolds each, that would really help. Is there anyway to do it in the current release? Or is it being planned for future releases??

Thank you,

Juan Montenegro

**Comment by vibansal** [comment]
The tool processes each contig/scaffold separately and there is no inbuilt option to run multiple scaffolds. The best way to run multiple scaffolds is to use a shell tool such as gnu parallel.
