### ISSUE TITLE
Feature request: add tags to bam rather than writing 3 separate files

### ISSUE THREAD

**Issue by wdecoster** [pjedge/longshot#35]
Hi,

Thanks for longshot, it's a great tool. I like the option to write out 3 bam files for the haplotype-separated reads, but have a related feature request.
Do you think it would be possible to write out only a single bam file, but adding tags to each read to specify both the haplotype and the phase block identifier?

Thanks,
Wouter

**Comment by vibansal** [comment]
Thanks for the feedback. We are in the process of adding this feature. The branch 'singlebam' has code to output a single bam with the haplotype (HP) tag. The phase block identifier is not output currently but should be added soon.

**Comment by wdecoster** [comment]
Thank you!

**Comment by vibansal** [comment]
The updated code that outputs the HP and PS tags is now on conda and master branch.

**Comment by wdecoster** [comment]
Thanks!
