### ISSUE TITLE
Feature request - multisample SNV calling

### ISSUE THREAD

**Issue by colindaven** [pjedge/longshot#37]
Hi, impressive and sorely needed tool - thanks.

I wonder if you are planning to implement multisample SNV calling in the future as this is very useful for comparison of multiple samples?

Thanks,
Colin

**Comment by vibansal** [comment]
Thanks for the feedback. This is not straightforward to implement since longshot jointly analyzes variants across long genomic regions and is not on our priority list.

**Comment by colindaven** [comment]
Ok, thanks for the reply, I'll look into a hacky alternative approach like recalling / pileups etc using the original BAMs and the longshot VCF as a target.
