### ISSUE TITLE
no output if 0 SNVs found

### ISSUE THREAD

**Issue by mike-molnar** [pjedge/longshot#42]
Hi,
I'm using snakemake with 10Mbp regions on human datasets, but there are a few regions for some datasets that have 0 SNVs.  Longshot exits without creating an output file, which causes problems for snakemake.  I would rather just have a file printed with the header so the snakemake workflow can still continue.

If I increase the size of my region to 30Mbp then there are no regions with 0 SNVs, but I would like to keep the regions small so everything can be run quickly (other programs use the same regions too).  Is it possible to include this enhancement, and include it in the conda repo (I'm trying to have conda handle the dependencies)?

Thanks

**Comment by vibansal** [comment]
This was reported previously (#38).  Conda version v0.4.1 should have fixed this issue. If not, please let us know.
