### ISSUE TITLE
thread 'main' panicked at 'assertion failed: p <= 0.0'

### ISSUE THREAD

**Issue by menickname** [pjedge/longshot#43]
I am currently using longshot for variant calling in a reference-based bacterial genome assembly pipeline. For most genomes longshot does not render issues. However for some genomes I encounter the following error:

`thread 'main' panicked at 'assertion failed: p <= 0.0'`

I am using ONT reads and have set the -P 0.01 value which does not lead to a solution in this case.

Thank you in advance.
Beste regards,
Nick Vereecke

**Comment by philres** [comment]
Hi,

I get the same error with a human dataset.

Would appreciate any help.

Thanks,
Philipp

**Comment by vibansal** [comment]
Can you share a small dataset that can reproduce this error?

**Comment by menickname** [comment]
Dear @vibansal 
When using long-read sequencing data (Nanopore) from viral origin, no problems occur upon implementation of longshot in the pipeline, nevertheless upon using it in a bigger dataset from bacterial origin, the error occurs. I got it again for a new dataset from another bacterial species. When using the complete dataset I got the error. This is an example of a few reads used in this analysis:
[subsample_data.fastq.zip](https://github.com/pjedge/longshot/files/4994332/subsample_data.fastq.zip)

**Comment by SegoleneDiry** [comment]
Hi,

I get the same error on a bacterial dataset using Longshot v4.0.1
Did you fix the issue? 

Thanks,

**Comment by menickname** [comment]
Dear @SegoleneDiry 

I am still waiting on a respons on my final answer on July 29.
Any update on this @vibansal 

Thank you in advance.

**Comment by vibansal** [comment]
If either of you can share a dataset (bam file and reference fasta) to reproduce this error, I would really like to fix it. You can upload the files to a secure OneDrive folder here[https://ucsdcloud-my.sharepoint.com/:f:/g/personal/vibansal_ucsd_edu/EvN8YiLlj_xDkDQSDYglzZsBzOSvifQj2I2qJTIEFpZZow](url)

**Comment by amandawarr** [comment]
I have the same problem with a virus. 

I can upload data. I've got one dataset that it will run on and one that it won't for the same reference.

**Comment by vibansal** [comment]
Thanks.

**Comment by vibansal** [comment]
Fixed. If you still encounter the error, please let us know.
