### ISSUE TITLE
structural variants

### ISSUE THREAD

**Issue by jdmontenegro** [pjedge/longshot#45]
Dear Peter,

Thank you for a very useful tool. I was wondering if you will add support for structural variants. Or if the current version can handle structural variants identified by other tools as a user-supplied VCF file. 

I am having a bit of problem trying to resolve a heterozygous regions with lost of repeats forming complex structural variants like tandem duplications, inversions, large INDELs. I am using around 34X coverage (17X per chromatid) and I have already identified quite a few of the heterozygous structural variatns, and would like to phase them using longshot.

Any suggestions on how to use Longshot for this, would be more than welcome.

Juan D. Montenegro

**Comment by vibansal** [comment]
Longshot is designed for small variants (SNVs and short indels). We don't plan to add support for SVs.
