### ISSUE TITLE
read names

### ISSUE THREAD

**Issue by jdmontenegro** [pjedge/longshot#46]
Hi,
thank you for this tool. It is working very nicely. One question though, what would happen if it is used on a polyploid specie where you can get more than 2 haplotypes? Is it able to estimate likelihood for more than two haplotypes? If not, would it be possible to write the names of the reads that support each SNV?

Cheers,

Juan D. Montenegro

**Comment by vibansal** [comment]
Longshot is designed for diploid genomes, its behavior on genomes with ploidy > 2 has not been evaluated.
