### ISSUE TITLE
Heterozygous non-ref variants

### ISSUE THREAD

**Issue by andreaminio** [pjedge/longshot#48]
Hi everyone,

I was testing the tool with a real-life dataset of CLR PacBio reads mapped with pbmm2. The results puzzle me a little as:

- I have no indels of sort in the calls (extremely unlikely to be true)
- Variants are never heterozygous alternative (1/2), just 0/1 or 1/1, eventually phased (quite unlikely to be true, as I'm comparing related species)

Is this expected to happen? Why? Is there any solution?

Another thing I noticed is that the depth of coverage of the alleles are reported in the INFO field but not in the sample call. This make the information get completely lost when merging the VCFs of different samples. Is there any way your tool can report the information along with the genotype call?

Andrea

**Comment by vibansal** [comment]
Longshot currently does not call indels or tri-allelic variants. 

We can add the depth of coverage to the genotype field in the next update. Thanks.

**Comment by andreaminio** [comment]
Well, 1/2 is a bialleleic variant. 
You mean that longshot only homozygous variants or heterozygous biallelic ones where one of the two alleles must be the reference? This is quite a limiting assumption.

**Comment by vibansal** [comment]
The depth of coverage is now also output in the genotype field (see master branch).

**Comment by jdmontenegro** [comment]
> Well, 1/2 is a bialleleic variant.
> You mean that longshot only homozygous variants or heterozygous biallelic ones where one of the two alleles must be the reference? This is quite a limiting assumption.

Hello guys, 

I am also very interested in this question. Can longshot manage non-reference biallelic variants? I would expect it does handle such a case, but I have not yet found any 1/2 genotypes in any of my tests. The reason I am very interested in this is to decide whether I can use as reference a genome of a different cultivar and after running longshot on chromosome, reassemble haplotypies separately. But I would not expect that haplotypes would necessarily include reference alleles, but rather different alleles.

**Comment by vibansal** [comment]
No, it does not. It only considers one non-reference allele as a variant. We are looking into adding this functionality.

**Comment by jdmontenegro** [comment]
Thank you. If there is something we can do to help, let us know to work
together. BTW, would it make sense to obtain a raw assembly (unpolished)
and then use it as a reference for longshot? That way we might actually get
a 0/1 heterozygous variants instead of using a high quality reference and
get a 1/2 het variants. Would that make sense, or would it still be better
to use the HQ reference genome?

Regards,

Juan D

**Comment by vibansal** [comment]
It would depend on how different the reference genome is from the genome sequenced and the rate of polymorphisms. If the divergence rate is high, using an assembly would be better.

**Comment by jdmontenegro** [comment]
Thank you,

They are the same species, but there is quite a bit of structural variation
between them. I will work with my current draft genome assembly to account
for the 1/2 het variants that would appear if I used the public reference
instead of our local assembly.

Cheers,

Juan D. Montenegro
