### ISSUE TITLE
VCF header is incorrect for genotype probabilities

### ISSUE THREAD

**Issue by cjw85** [pjedge/longshot#51]
The artic pipeline uses longshot after medaka to produce some ancilliary statistics of SARS-CoV-2 variants. The header associated with some probabilities incorrectly specifies some numbers as integer when in fact they are written as floats in teh records of the file, see https://github.com/nanoporetech/medaka/issues/213

From `src/print_output.rs`:

    let headerstr3 = format!("##INFO=<ID=PH,Number=G,Type=Integer,Description=\"PHRED-scaled Probabilities of Phased Genotypes\">

**Comment by phspo** [comment]
@cjw85 thanks for forwarding this to the correct place ;)

**Comment by vibansal** [comment]
Fixed in new release v0.4.2. Thanks.
