### ISSUE TITLE
VCF output missing header ##contig lines

### ISSUE THREAD

**Issue by omansn** [pjedge/longshot#54]
Hello, 
I suppose this is more of a feature request than bug.
It looks like the output VCF doesn't contain contig fields. Most command line VCF parsers (e.g. GATK, bcftools) require  contig fields even though it is optional under VCFv4.2.  Judging by the code, this isn't a bug. but just in case here are the parameters I used

`longshot -n -c 2 --ts_tv_ratio 2 -D 10:800:50 -E 0.05 -e 3 -r chr{} --bam minimap_bams/ADA_1_nanopore_passed.bam --ref genome.fa --out {}_ada1_longshot_out.vcf -d longshot/ada1/debug_{}`

**Comment by tprodanov** [comment]
It should work now!
