### ISSUE TITLE
Pair-HMM realignment: getting memory usage under control

### ISSUE THREAD

**Issue by ddrichel** [pjedge/longshot#60]
Hello Peter,

First of all, thank you for this beautiful piece of software.
 
Unfortunately, I am often running out of 120 GB of memory during pair-HMM realignment with ~30x coverage human ONT-sequenced and minimap2-aligned genomes:

`Calling initial genotypes using pair-HMM realignment...`
`Command terminated by signal 9`
`Command being timed: "/root/.cargo/bin/longshot --bam PC9.sorted_MD_RG.bam --ref GCA_000001405.15_GRCh38_no_alt_analysis_set.fna --out output_longshot_PC9/PC9_longshot.vcf"`

Are there "official" recommendations to trade memory requirements for running time and/or CPUs? I would not like to sacrifice accuracy but do not require phasing.

Thanks in advance

Dmitriy

**Comment by vibansal** [comment]
Longshot doesn't have significant memory requirements and should not typically be using such a large amount of memory. Have you tried running it on individual chromosomes/contigs using the --region option?

**Comment by ddrichel** [comment]
The previous example works with ~124 GB memory:
Maximum resident set size (kbytes): 124556572

Indeed it seems that there are cases when memory usage explodes.
Interestingly, I mostly see this in cancer cell lines rather then humans.
I will try to narrow down the problem.

**Comment by ddrichel** [comment]
Hello Peter,

I made a rough memory usage plot with the above mentioned sample and parameters, on an instance with 122GB of memory:

![longshot_wholesample](https://user-images.githubusercontent.com/15612230/117316548-fd192180-ae88-11eb-86a6-383be354f9a7.png)

Not sure why the memory consumption jumps up and down in between, the point is that the memory consumption suddenly jumps and longshot crashes.
  
Here is the same for consecutive runs with --region parameter, chromosomewise (and some missing data in the beginning):

![longshot_wholesample_chrwise](https://user-images.githubusercontent.com/15612230/117316523-f68aaa00-ae88-11eb-80c8-ad667e3513ac.png)

Memory consumption remains under control, so your workaround works for me, thank you.

I still see the problem only in cancer cells and not in healthy human tissue.
For practical purposes, I am now calling cancer cell lines with -v parameter and call references anyway, as SNP calling without given positions is difficult in general, with both long and short reads.
