### ISSUE TITLE
Criteria for INDEL heterozygosity

### ISSUE THREAD

**Issue by OgnjenMilicevic** [pjedge/longshot#61]
Hello,

As you probably know your caller is part of the ARTIC pipeline for SarsCov2. Since the virus is haploid, but heterozygous output has certain implications of interest (multistrain infection or bad call), I am very curious how this feature works. Unfortunately, a known variant of the B117 strain was called as heterozygous without any obvious reason. Please look at the two INDELs from VCF:

MN908947.3	21764	.	ATACATG	A	500.0	PASS	DP=1000;AC=90,898;AM=12;MC=0;MF=0.0;MB=0.0;AQ=20.82;GM=1;PH=6.02,6.02,6.02,6.02;SC=None;	GT:GQ:PS:UG:UQ	0/1:500.0:.:0/1:500.0
MN908947.3	21990	.	TTTA	T	500.0	PASS	DP=982;AC=89,843;AM=50;MC=0;MF=0.0;MB=0.0;AQ=15.36;GM=1;PH=6.02,6.02,6.02,6.02;SC=None;	GT:GQ:PS:UG:UQ	1/1:500.0:.:1/1:500.0

Longshot was run in --potential_variants mode on medaka output. Can you elaborate, if obvious, why one of the variants is heterozygous? How can we control for this?

**Comment by vibansal** [comment]
Longshot calculates the likelihood for each of the possible genotypes (0/0, 0/1, 1/1 for a bi-allelic variant) and uses these likelihoods to determine the most likely genotype. In this case, it seems that both variant have ~10% of the reads from the reference allele and 90% from the variant allele. If the error rate is low enough, the 10% of reads supporting the reference can be sufficient for the variant to be called as heterozygous (0/1). For the second variant, probably the error rate is high and therefore, it is called as homozygous-alternate (1/1).
