### ISSUE TITLE
Genotype for each variant

### ISSUE THREAD

**Issue by Raarbiarsan1899** [pjedge/longshot#65]
Hi! Is there an output give each read's genotype for each called SNV variant? I guess I can get genotypes from basecalled sequences but I guess many are ambiguous. Ex. 4000 reads have 2000 A's and 1000 G's at position 2333, but it is unclear how many A's and G's are confident while others are ambiguous.

I checked fragments.txt output from --variant_debug_dir option and don't quite understand what does each line mean.

2 6a4868cd-1276-430c-b62b-98c882119f7d_Basecall_1D_template:- 58 11010001 67 00111 .//////,./0,/

Here is my interpretation:
2 -- Haplotype
6a4868cd-1276-430c-b62b-98c882119f7d_Basecall_1D_template -- read_id
The length of '11010001' plus the length of '00111' equals the length of './/////,./0,/', so I guess './/////,./0,/' is Phred quality score?
What do 58 and 67 mean?

Thank you in advance!

**Comment by vibansal** [comment]
The fragments.txt follows the input file format used in HapCUT: https://github.com/vibansal/hapcut/blob/master/FAQ.md 

The format is also explained here: https://github.com/vibansal/HapCUT2/issues/40

58 and 67 are indexes (offsets) for the SNVs in the VCF file (2.0.realigned_genotypes.vcf file in the debug directory).

**Comment by Raarbiarsan1899** [comment]
So the genotypes in fragments.txt are final? I guess future haplotyping iterations won't change these genotypes right?

**Comment by Raarbiarsan1899** [comment]
> The fragments.txt follows the input file format used in HapCUT: https://github.com/vibansal/hapcut/blob/master/FAQ.md
> 
> The format is also explained here: [vibansal/HapCUT2#40](https://github.com/vibansal/HapCUT2/issues/40)
> 
> 58 and 67 are indexes (offsets) for the SNVs in the VCF file (2.0.realigned_genotypes.vcf file in the debug directory).

**Comment by Raarbiarsan1899** [comment]
Thank you!
