### ISSUE TITLE
Calling variants from supplementary alignments

### ISSUE THREAD

**Issue by bluenote-1577** [pjedge/longshot#68]
Hi there,

I am trying to call variants on small contigs output from long-read assembly. Most of the alignments onto these contigs are supplementary alignments as a result. In https://github.com/pjedge/longshot/issues/50#issuecomment-694375504 it is mentioned that supplemental alignments are filtered out, which explains why I'm not getting any variant calls. 

Is there an option to allow supplemental alignments to be used for variant calling? If there is an easy fix in the code I wouldn't mind fiddling around either. 

Thank you!

**Comment by vibansal** [comment]
Sorry for the delay in getting back on this question. 

An easy fix would be to change the flag value for supplemenary alignments in the input bam/cram file so that they are not supplementary anymore.
