### ISSUE TITLE
Memory issues with the tool

### ISSUE THREAD

**Issue by Mondlii** [pjedge/longshot#70]
Hi there, 

I am trying to use your tool for variant calling. I have 260x coverage of Nanopore data for a 680MB genome. The genome has been polished multiple times and haplotigs have been purged. Whenever I run the tool it runs for about 2 days and then gives an out of memory error. This usually happens after all variants have been called. I have tried running on servers with 450GB memory up to 780GB memory and 28 cores and the tool still dies out. I am new to bioinformatic analyses, so I would like assistance with this. Thank you.

Here is the command I ran:
longshot --bam Second_aligned.bam --ref /projects/Second_purge.fa --out longshot_output.vcf

Regards,
Mondli

**Comment by vibansal** [comment]
Can you try running on a single contig/chromosome to see if the same issue occurs? There is a command line option to specifiy a region. Thanks.

**Comment by Mondlii** [comment]
Hi, thank you for your response. I tried using a subsample of my data to about 80x coverage and the tool was able to run til it finished. Thank you.
