### ISSUE TITLE
Question about recommendation

### ISSUE THREAD

**Issue by caonetto** [pjedge/longshot#71]
Hi, in the help information there is a recommendation to run longshot through chromosomes separately using the region option. What is the underlying reason for this? Are the outputs going to be different if lets say a complete assembly is run when compared to the same assembly but separated by chromosomes? 

Cheers.

**Comment by vibansal** [comment]
This is primarily to reduce memory usage and run-time. Output could be slightly different  since the error rates are estimated from the input reads and used for all likelihood calculations.
