### ISSUE TITLE
can we use longshot to test  haploid SNP, even organelles

### ISSUE THREAD

**Issue by zhanghua1339** [pjedge/longshot#77]
Hi, dear authors,
Longshot is a good tool in variant calling for diploid genomes using PacBio and ONT.
Here I have a question that whether we can use this longshot to detect haploid SNP? 
I have some chloroplast and mitochondria samples in HiFi.
Can I use longshot directly in organelles or change some parameters ?
Thanks for your attention.
Please reply me in your spare time.

**Comment by vibansal** [comment]
Longshot can be used for haploid genomes with the --no-haps option.

**Comment by zhanghua1339** [comment]
Thank you, I will try to use it

**Comment by zhanghua1339** [comment]
Hi, dear authors,
I have tried SNP detecting using --no_haps. Compared with default parameter, it nearly has not change shown in VCF file.
I have some question ask you:
First, my demand is haploid (chloroplast) SNP calling, why we need to don't call HapCUT2 to phase variants(--no_haps)? what logic of it.
Second, I found you set max coverage : ‘mean_cov+5*sqrt(mean_cov)’ to filter in human, which decide the PASS or dn for every variant site in VCF file? Do you recommend the same max coverage calculation in haploid variant calling, or other new tactics.
Thank you so much for replying me.
Hua

**Comment by vibansal** [comment]
Phasing variants is applicable for diploid genomes, therefore it doesn't make sense to call hapcut2. The coverage filter is designed to remove variants in regions with high copy number, it works well for human genomes but we have not tested other genomes.
