### ISSUE TITLE
incorrectly calling homozygous genotype with low alternate alleles

### ISSUE THREAD

**Issue by ogrecio** [pjedge/longshot#78]
Hi, 
I am detecting variants from ONT reads, and I would like longshot to assign heterozygous even if the number of alternate reads is low (e.g, 3:1, or 5:2). However longshot keeps assigning reference genotype (0/0). I'm trying to use different parameters like -e 1 or -E 0.125, however the result does not change.

longshot -r $Chr -F --output-ref -v Reference-Beagle-fixed-SNPsMAF.vcf.gz --bam file.bam --ref reference.fa -o output.vcf --sample_id $sampleID -c 4 -y 7 -e 1 -E 0.125 -Q 7 -q 7 -a 7 -x -n

Could you please help me on how to make longshot to correctly assign heterozygous genotypes?
Thank you

Example: 
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth of reads passing MAPQ filter">
##INFO=<ID=AC,Number=R,Type=Integer,Description="Number of Observations of Each Allele">
##INFO=<ID=AM,Number=1,Type=Integer,Description="Number of Ambiguous Allele Observations">
##INFO=<ID=MC,Number=1,Type=Integer,Description="Minimum Error Correction (MEC) for this single variant">
##INFO=<ID=MF,Number=1,Type=Float,Description="Minimum Error Correction (MEC) Fraction for this variant.">
##INFO=<ID=MB,Number=1,Type=Float,Description="Minimum Error Correction (MEC) Fraction for this variant's haplotype block.">
##INFO=<ID=AQ,Number=1,Type=Float,Description="Mean Allele Quality value (PHRED-scaled).">
##INFO=<ID=GM,Number=1,Type=Integer,Description="Phased genotype matches unphased genotype (boolean).">
##INFO=<ID=PH,Number=G,Type=Float,Description="PHRED-scaled Probabilities of Phased Genotypes">
##INFO=<ID=SC,Number=1,Type=String,Description="Reference Sequence in 21-bp window around variant.">
##FILTER=<ID=dn,Description="In a dense cluster of variants">
##FILTER=<ID=dp,Description="Exceeds maximum depth">
##FILTER=<ID=sb,Description="Allelic strand bias">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=PS,Number=1,Type=Integer,Description="Phase Set">
##FORMAT=<ID=UG,Number=1,Type=String,Description="Unphased Genotype (pre-haplotype-assembly)">
##FORMAT=<ID=UQ,Number=1,Type=Float,Description="Unphased Genotype Quality (pre-haplotype-assembly)">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	barcode10
1	140870	.	C	T	1	PASS	DP=4;AC=3,1;AM=0;MC=0;MF=0.000;MB=0.000;AQ=20.20;GM=1;PH=0.00,42.61,81.57,86.41;SC=GCACTGATCACGTGGCTGATC;	GT:GQ:DP:PS:UG:UQ	0/0:43:4:.:0
/0:29.52
1	339540	.	C	T	1	PASS	DP=6;AC=4,2;AM=0;MC=0;MF=0.000;MB=0.000;AQ=21.83;GM=1;PH=0.00,80.71,37.76,80.70;SC=TATGTTTCCACTGACTGAAGC;	GT:GQ:DP:PS:UG:UQ	0/0:38:6:.:0
/0:9.21

**Comment by vibansal** [comment]
Longshot uses prior probabilities for heterozygous and homozygous genotypes for calculating genotype likelihoods (based on the command line parameters --hom_snv_rate and --het_snv_rate). For low coverage data, the posterior probabilities for non-reference genotypes are likely to be smaller than the reference (0/0) genotype. If you want to force these sites to be called as heterozygous, you can reduce the prior probability for the genotypes using the command line parameters.

**Comment by ogrecio** [comment]
Thank you vibansal. What range of prior probability should I choose?
I have used up to --hom_snv_rate 0.000001 --het_snv_rate 0.00001, but the results did not change.

**Comment by vibansal** [comment]
You need to increase the prior rather than decrease it to achieve the desired result.
