### ISSUE TITLE
Availability through conda?

### ISSUE THREAD

**Issue by KatSteinke** [pjedge/longshot#80]
Will 0.4.3 and any later versions be available through Conda at some point, so other tools using longshot can use an updated version more easily? I've started to run into the error described in issue #43  almost daily while running the ARTIC pipeline with longshot (0.4.1) activated in the last few days, for instance...

**Comment by aiershov** [comment]
I vote for this as well. 
There is a possibility to use dockerized longshot, it works, but for this you need to modify the longshot launch command in the algorithm, installing it with conda is much more simple.

**Comment by gianfilippo** [comment]
same issue here with longshot (0.4.1) and unable to update longshot with conda

**Comment by vibansal** [comment]
We have encountered some issues with compiling the 0.4.3 version on conda. We should be able to resolve these soon.

**Comment by gianfilippo** [comment]
thanks

**Comment by charlesfoster** [comment]
Hi there,

Thanks for developing longshot. Do you have any update on when versions >=0.4.3 might be available on conda? I'm using the latest available version on conda (0.4.1) and getting the `thread 'main' panicked at 'assertion failed: p <= 0.0'` error.
