### ISSUE TITLE
Homozygous sites

### ISSUE THREAD

**Issue by ettorefedele** [pjedge/longshot#83]
Hi,

I am new to longshot, I would like to use it to analyse my ONT sequencing data. I was wondering whether it was possible to extract loci with genotype 0/0 in known positions? Currently, it seems I can only have heterozygous and homozygous to the ALT sites in the final vcf.

Many thanks.

**Comment by vibansal** [comment]
If you run longshot with the -d option (variant_debug_dir), variants and genotypes at intermediate steps are written to separate files. The file 2.0.religned_genotypes.vcf has genotypes for 0/0 sites as well. If you want to genotype known positions, you can input a VCF file using the -v argument.
