### ISSUE TITLE
failed to create pileup

### ISSUE THREAD

**Issue by carolinehey** [pjedge/longshot#91]
Hi,
I have used longshot before without problems but now it gives me error messages. The cram file is created using a epi2me workflow.

martin@209a4324f86d:/data/longread/Caroline/sample10/ubam$ longshot -A -P --bam sample10.filtered.cram --region chr15 --ref /data/longread/Caroline/T2T-CHM13v2_reference.fasta --out_bam sample10_T2T_longshot.bam --out sample10_longshot.vcf

2022-10-18 11:38:03 Automatically determining max read coverage.
2022-10-18 11:38:03 Estimating mean read coverage...
[E::easy_errno] Libcurl reported error 60 (SSL peer certificate or SSH remote key was not OK)
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/914e0733351aaa9a4354ca8efb527401": Input/output error
[E::fai_build3_core] Failed to open the file /longread/Caroline/sample10/ubam/workspace/e3/7b717de1082c541c3103ae0e7dab2b/T2T-CHM13v2_reference.fasta
[E::refs_load_fai] Failed to open reference file '/longread/Caroline/sample10/ubam/workspace/e3/7b717de1082c541c3103ae0e7dab2b/T2T-CHM13v2_reference.fasta'
[E::cram_get_ref] Failed to populate reference for id 14
[E::cram_next_slice] Failure to decode slice
error: Error calculating mean coverage for BAM file.
caused by: Error reading BAM pileup.
caused by: failed to create SAM/BAM/CRAM pileup

Any idea what's going on?

**Comment by colindaven** [comment]
Not the dev, but looks like a cram problem. It can't find your reference FASTA. Can you convert to BAM and retry, that has solved similar problems for me with crams recently.
