### ISSUE TITLE
merging output.vcf: any best practices or tips? 

### ISSUE THREAD

**Issue by joanocha** [pjedge/longshot#94]
Hi,

Once I run longshot per chromosome per sample do you have any special recommendation for merging the vcfs in order to either get a full genome vcf per individual or a multi-sample vcf per chromosome? 

To be clear: I have been using deepVariant - which gives me one gvcf per sample - and  I jointly call genotypes with GLnexus to get a multi-sample vcf. Then I phase the multi-sample vcf with whatsHap. This is too time consuming and I wanted to try an alternative approach. Since longshot does variant calling + phasing all together how do I get from 1phased vcf per individual per chromosome into a multi-sample vcf? 

Thanks!

**Comment by vibansal** [comment]
chromosome-specific VCFs from longshot can be merged using bcftools concat (https://samtools.github.io/bcftools/bcftools.html#concat)

Also, 'bcftools merge' can merge VCF files from non-overlapping sample sets

**Comment by joanocha** [comment]
Great thanks! Indeed I have been using these following longshot snv. It’s
nice to have the reassurance that bcftools is suitable for merging and/or
concat .
