### ISSUE TITLE
"Error creating augmented cigarlist"

### ISSUE THREAD

**Issue by laetitiarialland** [pjedge/longshot#98]
Hello, 

I was trying to run LongShot on Long-Read Nanopore data (for RNA sequencing) aligned with ultra (https://github.com/ksahlin/ultra). 

When I run longshot with basis parameters :
longshot --bam /scratchbeta/rialland/LR_SEQ/u_PIL4_1.bam --ref /scratchbeta/rialland/GRCh38.p13.fa --out P41_longshot.vcf

It doesn't work and generates this error : 
2024-02-20 11:16:17 Min read coverage set to 6.
2024-02-20 11:16:17 Max read coverage set to 8000.
2024-02-20 11:16:17 Estimating alignment parameters...
error: Error estimating alignment parameters.
caused by: Error creating augmented cigarlist.
caused by: Unexpected CIGAR operation: 'reference skip' (N) found before any operation describing read sequence

Does somebody ever meet this issue or can help ? 

Thank you,

Laëtitia

**Comment by vibansal** [comment]
It seems that the aligned reads have a 'N' (reference_skip) as the first operation in the cigar string. This is not expected since reference_skip is usually for skipping over introns.
